parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
hwi_oauth:
    firewall_names: [main]
    fosub:
        properties:
            facebook: facebookId
            google: googleId
    resource_owners:
        facebook:
            type:                facebook
            client_id:           your_facebook_client_id
            client_secret:       your_facebook_client_secret
            options:
                display: popup
                auth_type: rerequest
                csrf: true
        google:
            type:                google
            scope:               "your wanted scope" # example : https://www.googleapis.com/auth/userinfo.email
            client_id:           your_google_client_id
            client_secret:       your_google_client_secret
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"