parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
hwi_oauth:
    firewall_names: [main]
    fosub:
        properties:
            facebook: facebookId
            google: googleId
    resource_owners:
        facebook:
            type:                facebook
            client_id:           2076571935898183
            client_secret:       8b2be8a7b02fcc4812fb2fdfb7628fe5
            options:
                display: popup
                auth_type: rerequest
                csrf: true
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
web_profiler:
    toolbar: true
    position: bottom
    intercept_redirects: false