security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    User:
                        password: user
                        roles: 'ROLE_USER'
                    Admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
        fos_userbundle:
            id: fos_user.user_provider.username
    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/check-facebook, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: chain_provider
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: dashboard
            logout:
                path: /logout
                target: /
            oauth:
                resource_owners:
                    facebook:      facebook_login
                login_path:        fos_user_security_login
                failure_path:      fos_user_security_login

                oauth_user_provider:
                    service: app.fos_user.oauth_provider
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER