security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        chain_provider:
            chain:
                providers: [in_memory]
        in_memory:
            memory:
                users:
                    User:
                        password: user
                        roles: 'ROLE_USER'
                    Admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/check-facebook, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login/check
                default_target_path: dashboard
            logout:
                path: /logout
                target: /
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER